<?php

/**
 * @file
 * Contains constant_contact_campaign.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help
 *
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *
 * @return string
 */
function constant_contact_campaign_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  switch ($route_name) {
    case 'help.page.constant_contact_campaign':
      $output .= '';
      break;
  }
  return $output;
}

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function constant_contact_campaign_form_node_constant_contact_campaign_form_alter(&$form, FormStateInterface $form_state) {

  $form['actions']['submit']['#submit'][] = "campaign_submitted_values";
}

function campaign_submitted_values(&$form, FormStateInterface $form_state){
  $campaignManager = \Drupal::service('constant_contact_campaign.manager');
  $campaignManager->createEmailCampaign();
}